### ISSUE TITLE
don't build on kali 2018.3a - missing "NetworkManager.h"

### ISSUE THREAD

**Issue by RobertoD91** [routerkeygen/routerkeygenPC#45]
Hi, on kali 2018.3a, even after installing `network-manager-dev` i get this error:
```
[ 93%] Building CXX object src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o
In file included from /root/Desktop/routerkeygenPC/src/wifi/QWifiManager.cpp:31:
/root/Desktop/routerkeygenPC/src/wifi/QWifiManagerPrivateUnix.h:16:10: fatal error: NetworkManager.h: File o directory non esistente
 #include <NetworkManager.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/routerkeygen.dir/build.make:863: src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:218: src/CMakeFiles/routerkeygen.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
Error while building
```

**Comment by tsiebecker** [comment]
4.19.0-kali1-amd64 , exactly the same

`[ 93%] Building CXX object src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o
In file included from /root/Downloads/routerkeygenPC/src/wifi/QWifiManager.cpp:31:
/root/Downloads/routerkeygenPC/src/wifi/QWifiManagerPrivateUnix.h:16:10: fatal error: NetworkManager.h: Datei oder Verzeichnis nicht gefunden
 #include <NetworkManager.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/CMakeFiles/routerkeygen.dir/build.make:863: src/CMakeFiles/routerkeygen.dir/wifi/QWifiManager.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:218: src/CMakeFiles/routerkeygen.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2
Error while building`

**Comment by RealEnder** [comment]
Can you build the commandline version?
https://github.com/routerkeygen/routerkeygenPC#commandline-version

**Comment by tsiebecker** [comment]
Yes, building the cli version was possible without the "fix" from above. But in Kali is "libnm-gtk-dev" non-exsistent. So installing the requirements like written in the README is not possible.
Solution: 

`sudo apt-get install -y cmake build-essential qt5-default libssl-dev qtscript5-dev qttools5-dev qttools5-dev-tools rpm lintian`

cli version builds without it, for other version see fix.

P.S.: @RealEnder Big fan, keep up the good work.
